---
kind: pipeline
type: docker
name: lint
steps:
  - name: Lint Dockerfile
    image: hadolint/hadolint:latest-alpine
    pull: if-not-exists
    commands:
      - hadolint --version
      - hadolint Dockerfile*

---

kind: pipeline
type: docker
name: latest

platform:
  os: linux
  arch: amd64

steps:
- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/docker-rickroll:latest"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest

trigger:
  event:
  - cron
  cron:
  - rickroll_latest

depends_on:
  - lint

---

kind: pipeline
type: docker
name: monthly

platform:
  os: linux
  arch: amd64

steps:
- name: monthly  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/docker-rickroll:monthly"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: monthly

trigger:
  event:
  - cron
  cron:
  - rickroll_monthly

depends_on:
  - lint

---

kind: pipeline
type: docker
name: Youtube

platform:
  os: linux
  arch: amd64

steps:
- name: youtube  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    use_cache: true
    cache_from: "modem7/docker-rickroll:youtube"
    platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
    dockerfile: youtube/Dockerfile
    context: youtube/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: youtube

trigger:
  event:
  - cron
  cron:
  - rickroll_youtube

depends_on:
  - lint