---

kind: pipeline
type: docker
name: latest

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint ./SD/piholeunbound/Dockerfile*

- name: latest  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    squash: true
    use_cache: true
    cache_from: "modem7/docker-rickroll:latest"
    dockerfile: SD/Dockerfile
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

# trigger:
  # event:
  # - cron
  # cron:
  # - rickroll_latest

---

kind: pipeline
type: docker
name: Onclick

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint ./SD/onclick/Dockerfile*

- name: onclick  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    use_cache: true
    squash: true
    cache_from: "modem7/docker-rickroll:onclick"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    dockerfile: SD/onclick/Dockerfile
    # context: onclick/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: onclick

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - rickroll_onclick

---

kind: pipeline
type: docker
name: Youtube

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint ./youtube/Dockerfile*

- name: youtube  
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    use_cache: true
    squash: true
    cache_from: "modem7/docker-rickroll:youtube"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    dockerfile: youtube/Dockerfile
    context: youtube/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: youtube

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - rickroll_youtube

---

kind: pipeline
type: docker
name: 1080

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint ./1080/Dockerfile*

- name: 1080
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    use_cache: true
    squash: true
    cache_from: "modem7/docker-rickroll:1080"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    dockerfile: 1080/Dockerfile
    # context: onclick/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 1080

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - rickroll_1080

---

kind: pipeline
type: docker
name: 1080onclick

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint ./1080/onclick/Dockerfile*

- name: 1080onclick
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    use_cache: true
    squash: true
    cache_from: "modem7/docker-rickroll:1080onclick"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64/v8
    dockerfile: 1080/onclick/Dockerfile
    # context: onclick/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 1080onclick

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  event:
  - cron
  cron:
  - rickroll_1080onclick

---

kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: Lint Dockerfile
  image: hadolint/hadolint:latest-alpine
  pull: if-not-exists
  commands:
    - hadolint --version
    - hadolint ./test/Dockerfile*

- name: test build
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/docker-rickroll
    purge: true
    compress: true
    # use_cache: true
    # cache_from: "modem7/docker-rickroll:test"
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      # - linux/arm/v6
      # - linux/arm/v7
      # - linux/arm64/v8
    dockerfile: test/Dockerfile
    # context: test/
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: test

trigger:
  branch:
  - test